### ISSUE TITLE
Expose event so user can choose to preventDefault

### ISSUE THREAD

**Issue by cmmartin** [haldarmahesh/use-key-hook#13]
In certain situations, you want to call `event.preventDefault()` and handle the keypress yourself. You can't do this currently, because you have no access to the actual key event. Perhaps we could pass it as the second argument to the `useKey` callback?

```javascript
useKey((pressedKey, event) => {
   event.preventDefault()
   ...
}, {
   detectKeys: [...]
});
```

**Comment by haldarmahesh** [comment]
@cmmartin That's a great recommendation, this will give more control to one who is using this.
Thanks

We will target to release the next version with this.

**Comment by haldarmahesh** [comment]
@cmmartin 
The new version 1.4.0 is available which includes this feature.
Thanks @liquid-mike for raising PR.
