### ISSUE TITLE
Is this supposed to be used for local key press events ?

### ISSUE THREAD

**Issue by gaurav5430** [haldarmahesh/use-key-hook#16]
The use cases listed in Readme are mostly related to 

1. when there is a single component on screen. (music player)
2. when the key events are global (escape)

do you think we can use this for something like a checkbox, which should change state based on space key press ?

it seems that the problem in those cases would be to check if the element is in focus and only run the effects then, or is this not supposed to be used in such scenarios at all , and we should just be using keypress on the particular element.

**Comment by haldarmahesh** [comment]
Hey, this is not only for local or specific to the only component, but this can also be composed easily with other components, as that is the guiding principle of React.

Use `useRef` hook along with `useKeyHook` to get the reference of any input like a checkbox in your case and toggle its state easily.

I am closing this, for now, let me know if you need help, can share the code piece with you.

You can reopen if your question is not answered.
Thanks
