### ISSUE TITLE
onKeyUp, onKeyPress functionalities

### ISSUE THREAD

**Issue by parthsr** [haldarmahesh/use-key-hook#2]
Is it good to have onKeyUp, onKeyPress functionalities as well?

**Comment by sagar-gavhane** [comment]
I agree with @parthsr , we should have onKeyUp and onKeyPress events.

**Comment by haldarmahesh** [comment]
I agree with you @parthsr, we should have more APIs so that it can cover more scenarios.

I am adding the label of feature request so that this can be picked up and released in the future release.

Thanks for raising it.

**Comment by gurschitz** [comment]
A possibility to solve this easily would be to pass the type of keyevent as a configuration (defaulting to keydown?). 

I don't think it's necessary to handle more than one event with one hook call. You can just call the hook another time with a different event, if you need to cover more events.

The events that should be covered imo are just `keydown`,`keypress` and `keyup`

If you agree with this @haldarmahesh, I could implement this.

**Comment by haldarmahesh** [comment]
> I don't think it's necessary to handle more than one event with one hook call. You can just call the hook another time with a different event, if you need to cover more events.

@gurschitz I agree with you on this point 👍 

> The events that should be covered imo are just `keydown`,`keypress` and `keyup`

Let's do these 3.

I agree with you and will be happy, if you can raise a PR.

Thanks.
Meanwhile, I will update README file with list of contributors and contributing guidelines.

Thanks @parthsr for creating this ticket.

**Comment by haldarmahesh** [comment]
This feature is added in v @1.3.4
Thanks, @gurschitz for raising PR and @parthsr for creating this feature request.

Cheers 🍻
