### ISSUE TITLE
Set state in callback

### ISSUE THREAD

**Issue by jurajkrivda** [haldarmahesh/use-key-hook#20]
Hi there. Could you help me with the implementation of this hook? How can I set state in callback? For example, press "a" key I want to increment number, press "d" I want to decrement the same state number. Thank you.

**Comment by haldarmahesh** [comment]
Hey @jurajkrivda, you can refer the documentation to understand how to use this hook.

If you want an exact example of how to use set state with this hook you can refer the demo page for this hook, where I am incrementing the count of the key pressed.

The link of the source code is:

https://github.com/haldarmahesh/demo-use-key/blob/master/src/use-key/index.js

Please let me know if this helps.

Happy to help more.
Thanks

**Comment by haldarmahesh** [comment]
Hey @jurajkrivda closing it, for now, let me know if this helps or reopen the issue if this doesn't helps you.
Thanks
