### ISSUE TITLE
Event listener not removed correctly

### ISSUE THREAD

**Issue by gurschitz** [haldarmahesh/use-key-hook#9]
I am using this hook to update a state when a key is pressed, and I ran into the issue that the state is still being updated even though my component has been unmounted. I think it's because the event listener for the keyboard event is not removed correctly. React then logs a warning: ```Warning:  Can't perform a React state update on an unmounted component (...)```

If `removeEventListener` is called with the same function as `addEventListener`, then it works. (I've confirmed that with a forked version of this).

I'm happy to make a pull request for this. I'm not sure how to test this correctly though, I've tried writing a test for this, but I wasn't able to get it working. That's why I suggest using [react-testing-library](https://www.npmjs.com/package/react-testing-library) for this and test the hook in a component. It would allow to not test the `addEventListener` / `removeEventListener` directly (which is an implementation detail imo), but rather test the component and the interaction with it. 

For this it would be convenient to use babel so that we can just render the component in the test files using jsx. I'm also happy to set this up.

Let me know what you think, I'd love to get feedback from you before I make a pull request for this. :)

**Comment by haldarmahesh** [comment]
Hey @gurschitz , thanks for reporting this issue.
This looks weird and is unexpected.
Let me also try to replicate and know why exactly this is happening. 
I will be more than happy if you raise a PR to fix this.
And also lets invest time to write a test case for the same.
Thanks

**Comment by haldarmahesh** [comment]
This issue is fixed and new version 1.1.0 is published.
Thanks, @gurschitz for the PR.

**Comment by gurschitz** [comment]
Thanks. Happy to help :)
